name: Build on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - profile: linux-gcc13-x86_64-release
            runs-on: ubuntu-latest
    uses: ./.github/workflows/build.yml
    with:
      profile: ${{ matrix.profile }}
      runs-on: ${{ matrix.runs-on }}
      build_type: Release
