name: Build on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: debian-gcc13-x86_64-release
            runs-on: ubuntu-latest
            container_image: debian:13
            package_manager: apt

          - profile: alpine-gcc15-x86_64-release
            runs-on: ubuntu-latest
            container_image: alpine:3.23
            package_manager: apk

    uses: ./.github/workflows/build.yml
    with:
      profile: ${{ matrix.profile }}
      runs-on: ${{ matrix.runs-on }}
      build_type: Release
      container_image: ${{ matrix.container_image }}
      package_manager: ${{ matrix.package_manager }}
