name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - profile: linux-gcc13-x86_64-release
            runs-on: ubuntu-latest
          - profile: linux-gcc13-arm64-release
            runs-on: ubuntu-latest-arm64
    uses: ./.github/workflows/build.yml
    with:
      profile: ${{ matrix.profile }}
      runs-on: ${{ matrix.runs-on }}
      build_type: Release

  publish-release:
    name: Publish ${{ matrix.alias }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - alias: linux-x86_64
            profile: linux-gcc13-x86_64-release
          - alias: linux-arm64
            profile: linux-gcc13-arm64-release
    if: success()

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: build-${{ matrix.profile }}
          path: artifact

      - name: Upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          file=$(ls artifact/*)
          filename=$(basename "$file")
          renamed_file="${filename%.*}-${{ matrix.alias }}${filename##*.}"
          mv "$file" "$renamed_file"
          gh release upload "$tag_name" "$renamed_file" --clobber
