name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - profile: debian-gcc13-x86_64-release
            runs-on: ubuntu-latest
            container_image: debian:13
            package_manager: apt

          - profile: alpine-gcc15-x86_64-release
            runs-on: ubuntu-latest
            container_image: alpine:3.23
            package_manager: apk

    uses: ./.github/workflows/build.yml
    with:
      profile: ${{ matrix.profile }}
      runs-on: ${{ matrix.runs-on }}
      build_type: Release
      container_image: ${{ matrix.container_image }}
      package_manager: ${{ matrix.package_manager }}

  publish-release:
    name: Publish ${{ matrix.alias }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        include:
          - alias: debian-x86_64
            profile: debian-gcc13-x86_64-release
          - alias: alpine-x86_64
            profile: alpine-gcc15-x86_64-release
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: build-${{ matrix.profile }}
          path: artifact

      - name: Upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          echo $tag_name
          file=$(ls artifact/*)
          filename=$(basename "$file")
          renamed_file="${{ matrix.alias }}-${filename}"
          mv "$file" "$renamed_file"
          echo $renamed_file
          gh release upload "$tag_name" "$renamed_file" --clobber
